services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8080:80"

  kalilinux:
    build: ./kalilinux
    ports:
      - "9090:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  devtools-fieldtest:
    build: ./docker/devtools-fieldtest
    ports:
      - "7070:80"


  devtools-guided:
    build: ./docker/devtools-guided
    ports:
      - "6060:80"

  recon-ng:
    build: ./docker/recon-target
    ports:
      - "5050:80"

  idor-lab:
    build: ./docker/idor-lab
    ports:
      - "4040:80"

  nmap-target:
    build: ./docker/nmap-target
    ports:
      - "8880:80"
      - "31337:31337"

  nmap-deepdive:
    build: ./docker/nmap-deepdive
    ports:
      - "8881:80"
      - "2121:21"
      - "54321:54321"

